### ISSUE TITLE
`vagrant up` doesn't start

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/fedora-packages#394]
Putting aside https://bugzilla.redhat.com/show_bug.cgi?id=1605016 `vagrant up` still doesn't start, because of some problem with referenced image.
```
✗ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'f25-cloud-libvirt' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'f25-cloud-libvirt' (v0) for provider: libvirt
    default: Downloading: https://download.fedoraproject.org/pub/fedora/linux/releases/25/CloudImages/x86_64/images/Fedora-Cloud-Base-Vagrant-25-1.3.x86_64.vagrant-libvirt.box
==> default: Box download is resuming from prior download progress
#<Thread:0x00005624bbb75148@/usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        47: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
...
         2: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/box_collection.rb:137:in `block (3 levels) in add'
         1: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/box_collection.rb:137:in `new'
/usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/box.rb:65:in `initialize': The "metadata.json" file for the box 'f25-cloud-libvirt' was not found. (Vagrant::Errors::BoxMetadataFileNotFound)
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:
 
https://www.vagrantup.com/docs/boxes/format.html
The "metadata.json" file for the box 'f25-cloud-libvirt' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:
 
https://www.vagrantup.com/docs/boxes/format.html
```
Full trace - https://pastebin.mozilla.org/9090160

**Comment by abitrolly** [comment]
Running `vagrant up --debug` revealed problem with `bsdtar` and then I found that it is 0 length. Reinstalling `bsdtar` package fixed the problem.

**Comment by cverna** [comment]
We should probably change the base image to use fedora 28 instead of fedora 25 which is EOL
