### ISSUE TITLE
`sudo python setup.py develop` fails on F29

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/fedora-packages#412]
https://apps.fedoraproject.org/packages/python-webob is 1.8.2 which fails requirements.

```
$ sudo python setup.py develop
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'authors'
  warnings.warn(msg)
running develop
running egg_info
writing requirements to fedoracommunity.egg-info/requires.txt
writing fedoracommunity.egg-info/PKG-INFO
writing top-level names to fedoracommunity.egg-info/top_level.txt
writing dependency_links to fedoracommunity.egg-info/dependency_links.txt
writing entry points to fedoracommunity.egg-info/entry_points.txt
Traceback (most recent call last):
  File "setup.py", line 142, in <module>
    """
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/usr/lib/python2.7/site-packages/setuptools/command/develop.py", line 134, in install_for_development
    self.run_command('egg_info')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/usr/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/usr/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 573, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/usr/lib/python2.7/site-packages/setuptools/command/sdist.py", line 20, in walk_revctrl
    for item in ep.load()(dirname):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2331, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (WebOb 1.8.2 (/usr/lib/python2.7/site-packages), Requirement.parse('WebOb<1.8.0,>=1.2'), set(['TurboGears2']))
```

**Comment by cverna** [comment]
yes it needs a to use the version of Turbogears2 from the master branch, they have added support for Web0b > 1.8.0 but did not release it yet.

I have a update waiting for the Turbogears2 rpm package --> https://bodhi.fedoraproject.org/updates/FEDORA-2019-5ef7b30741

**Comment by abitrolly** [comment]
I have a feeling that Turbogears2 and Mocha are losing grounds to React and friends. As an external contributor who needs to do Freelance and coding on proprietary projects for a living, I had to spend my time with MIT-like projects, where I can not only learn popular framewoks like Flask and vue.js, but also reuse the snippets.

**Comment by cverna** [comment]
> I have a feeling that Turbogears2 and Mocha are losing grounds to React and friends. As an external contributor who needs to do Freelance and coding on proprietary projects for a living, I had to spend my time with MIT-like projects, where I can not only learn popular framewoks like Flask and vue.js, but also reuse the snippets.

Totally agree and this is why I started [fedora-search](https://github.com/fedora-infra/fedora-search) (django rest framework backend) that will be used by a reactjs app, then we can archive this project. I just lack of time to start working on the frontend.

**Comment by abitrolly** [comment]
https://github.com/fedora-infra/fedora-search is GPL, and I don't have any GPL-friendly clients for an incentive to learn this codebase.
