### ISSUE TITLE
cache-worker: IOError: [Errno 107] Transport endpoint is not connected: '/var/cache/fedoracommunity/bugzillacookies'

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/fedora-packages#61]
I'm seeing this exception in production. I'm guessing it's gluster-related.

```python
ERROR:fcomm-cache-worker:Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/fedoracommunity/connectors/api/worker.py", line 105, in run
    self.iteration()
  File "/usr/lib/python2.6/site-packages/fedoracommunity/connectors/api/worker.py", line 87, in iteration
    value = fn(**data['kw'])
  File "/usr/lib/python2.6/site-packages/fedoracommunity/connectors/bugzillaconnector.py", line 255, in query_bugs
    **params
  File "/usr/lib/python2.6/site-packages/fedoracommunity/connectors/bugzillaconnector.py", line 282, in _query_bugs
    _results = self._bugzilla.query(query)
  File "/usr/lib/python2.6/site-packages/fedoracommunity/connectors/bugzillaconnector.py", line 64, in _bugzilla
    return Bugzilla(url=self._base_url, cookiefile=self._cookiefile)
  File "/usr/lib/python2.6/site-packages/bugzilla/rhbugzilla.py", line 52, in __init__
    _parent.__init__(self, **kwargs)
  File "/usr/lib/python2.6/site-packages/bugzilla/bugzilla4.py", line 24, in __init__
    Bugzilla36.__init__(self, **kwargs)
  File "/usr/lib/python2.6/site-packages/bugzilla/bugzilla3.py", line 24, in __init__
    BugzillaBase.__init__(self, **kwargs)
  File "/usr/lib/python2.6/site-packages/bugzilla/base.py", line 277, in __init__
    self.cookiefile = cookiefile
  File "/usr/lib/python2.6/site-packages/bugzilla/base.py", line 356, in _setcookiefile
    self._cookiejar = _build_cookiejar(cookiefile)
  File "/usr/lib/python2.6/site-packages/bugzilla/base.py", line 75, in _build_cookiejar
    open(cookiefile, 'a').close()
IOError: [Errno 107] Transport endpoint is not connected: '/var/cache/fedoracommunity/bugzillacookies'
```

**Comment by ralphbean** [comment]
I killed the cache worker, so this isn't an issue anymore.
